ignore tests on windows, CI of Windows is not compatible:
[crates\node-bindings\src\nodes\reth.rs:369:13] &line = "2024-09-04T12:39:10.637528Z  INFO reth::cli: Opening database path=\"C:\\\\Users\\\\RUNNER~1\\\\AppData\\\\Local\\\\Temp\\\\.tmp4XoSee\\\\db\"\n"
[crates\node-bindings\src\nodes\reth.rs:369:13] &line = "2024-09-04T12:39:10.731699Z ERROR reth::cli: shutting down due to error\n"
Error: failed to open the database: environment or database is not compatible with the requested operation or flags (-30784)

Location:
    /project/crates/storage/db/src/mdbx.rs:28:8