feat: add Reth node bindings (#1092)
* generalize geth into node

* add basic reth setup

* basic spawning and capturing of ports works, shutdown does not

* add auth_port, p2p_port

* clean up

* fix geth tests

* simplify abstraction

* clean up

* add explicit `dev` mode command, reth remains open

* --chain takes path or string, not id

* add support for UDP endpoint extraction from keys

* clean up, add dev flag

* tag as dev

* add option to set block time

* add block time

* disable peer persistence if discovery is disabled

* update binaries

* add reth install in github workflow

* fix build

* fix doctest

* windows geth build is zipped

* fix name

* fix path to reth binary

* tar is flat

* fix url

* fix output path

* reth is already extracted to the root

* reth renders via stdout

* disable dev by default, enabling it with .dev()

* make sure to exit when running into fatal error

* add tests to cover the feature set

* try debugging windows

* run binary install in parallel

* disable discovery on blocktime dev

* attempt to fix on windows by not using tempdir

* re-enable tempdir, attempt to get full error log on windows

* ignore tests on windows, CI of Windows is not compatible:

[crates\node-bindings\src\nodes\reth.rs:369:13] &line = "2024-09-04T12:39:10.637528Z  INFO reth::cli: Opening database path=\"C:\\\\Users\\\\RUNNER~1\\\\AppData\\\\Local\\\\Temp\\\\.tmp4XoSee\\\\db\"\n"
[crates\node-bindings\src\nodes\reth.rs:369:13] &line = "2024-09-04T12:39:10.731699Z ERROR reth::cli: shutting down due to error\n"
Error: failed to open the database: environment or database is not compatible with the requested operation or flags (-30784)

Location:
    /project/crates/storage/db/src/mdbx.rs:28:8

* only install on linux

* temporarily re-enable windows to test error catching

* revert